Version 0.1
Dhii/espresso-interface pull request #1
Opened 2017-01-21 19:18 UTC by mecha

Initial release.

2017-01-22 11:16 UTC, XedinUnknown commented on README.md
> +
What about CodeClimate?

2017-01-22 11:18 UTC, XedinUnknown requested changes
Should `ContextInterface` extend `ValueAwareInterface`?

2017-01-22 11:57 UTC, mecha commented on README.md
> +
Didn't yet add the repo to CodeClimate. Currently checking if we can share administration of repos registered in CC.

2017-01-22 11:59 UTC, mecha commented
Yes. In fact, it should already be extending it 😕

Which is odd because dependents that extend `EvaluableInterface` depend on `ValueAwareInterface` not `ContextInterface` ... and yet their tests pass.

2017-01-22 12:08 UTC, XedinUnknown commented on README.md
> +
I added everything

2017-01-22 12:09 UTC, XedinUnknown commented
@mecha, I know, right!? I saw code that depends on `ValueAwareInterface`. Dunno why this isn't there.

2017-01-22 12:10 UTC, XedinUnknown commented
I'm on Gitter, by the way, but you haven't replied since yesterday...

2017-01-22 12:25 UTC, XedinUnknown approved these changes

2017-01-23 00:57 UTC, merged

2017-01-23 10:59 UTC, XedinUnknown commented on composer.json
>          "php": "^5.3.9 | ^7.0",
Is there a reason why min requirement is specifically PHP 5.3.*9*? I didn't find cases of method overriding. With the exception of [`ContextInterface#getValue()`](https://github.com/Dhii/espresso-interface/blob/master/src/ContextInterface.php#L21), which I don't know why it is there. Could you explain please?

2017-01-23 11:04 UTC, mecha commented on composer.json
>          "php": "^5.3.9 | ^7.0",
I usually use `5.3.9` in interface packages regardless of whether there is method overriding or not.  Probably a bad habit of mine.

`ContextInterface#getValue()` seems to be a remnant of when `ContextInterface` didn't extend `ValueAwareInterface`. Looks like I forgot about it.

2017-01-23 11:05 UTC, XedinUnknown commented on composer.json
>          "php": "^5.3.9 | ^7.0",
@mecha, one way to fix this could be to file a new PR for the release branch, and merge again after the fix.

2017-01-23 11:31 UTC, XedinUnknown commented
@mecha, following our discussion on Gitter, please re-name project to `dhii/expression-interface`, and re-factor the code.